import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Manrope } from "next/font/google";
import NavbarLayout from "./(navbarlayout)/NavbarLayout";
import NextTopLoader from "nextjs-toploader";
const manrope = Manrope({ subsets: ["latin"] });
import { ReactQueryProvider } from "@/utils/react-query-provider";

export const metadata = {
  title: "Fund Allocation System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <ReactQueryProvider>
          <div className="bg-light-white-100">
            <NextTopLoader color="#518554" height={5} showSpinner={false} />
            <NavbarLayout>
              {children}
              <ToastContainer theme="colored" position="bottom-right" autoClose={1000}/>
            </NavbarLayout>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
